/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectppdb;

/**
 *
 * @author Deddy
 */
public class Daftar extends javax.swing.JPanel {

    /**
     * Creates new form Daftar
     */
    public Daftar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eml = new javax.swing.JTextField();
        jk = new javax.swing.JTextField();
        almt = new javax.swing.JTextField();
        nl = new javax.swing.JTextField();
        dftr = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emlActionPerformed(evt);
            }
        });
        add(eml, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 450, 30));

        jk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkActionPerformed(evt);
            }
        });
        add(jk, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 450, 40));

        almt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                almtActionPerformed(evt);
            }
        });
        add(almt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 450, 30));

        nl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nlActionPerformed(evt);
            }
        });
        add(nl, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 450, 30));

        dftr.setBorderPainted(false);
        dftr.setContentAreaFilled(false);
        dftr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(dftr, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/ptongan.jpeg"))); // NOI18N
        jLabel1.setToolTipText("");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 451));
    }// </editor-fold>//GEN-END:initComponents

    private void emlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emlActionPerformed

    private void jkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jkActionPerformed

    private void almtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_almtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_almtActionPerformed

    private void nlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nlActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField almt;
    private javax.swing.JButton dftr;
    private javax.swing.JTextField eml;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jk;
    private javax.swing.JTextField nl;
    // End of variables declaration//GEN-END:variables
}
